### ISSUE TITLE
need extra linker flags on Centos 8

### ISSUE THREAD

**Issue by ghost** [mpartel/postgres-protobuf#2]
Hi,

more an Info than an Issue...

To compile  postgres-protobuf 0.2.0 to be used with a Postgres 11.7 compiled from source on Centos 8 (8.1.1911) with g++ (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4) I needed to add the two arguments

`-lz -lstdc++
`

to the PG_LDFLAGS line in the Makefile.

Otherwise I would get undefined symbols when executing CREATE EXTENSION.

Thanks,
Chris.

**Comment by mpartel** [comment]
Thanks! Strange that they're not required on Ubuntu :man_shrugging:
