### ISSUE TITLE
decoding floats loses precision

### ISSUE THREAD

**Issue by ghost** [mpartel/postgres-protobuf#4]
Hi,

thanks for the nice extension!

I've found a problem related to floats... When floats are decoded to text by protobuf_query() or 
protobuf_query_array() precision is (heavily) lost.!

The floats appear to be decoded here:

https://github.com/mpartel/postgres-protobuf/blob/d8c1c16a6ce821d2a1b10a1f7146d27138468e12/querying.cpp#L429

using std::to_string(), which corresponds to sprintf("%f", ..) and would always print with six digits right to the decimal point.

So, for example a value like 1.0E-7 just get decoded to the text '0.000000' :(

I'm going to need to patch around this for my use case, maybe with a custom sprintf("%e", ..) for floats in particular.

Do you have any suggestion? 

I would be willing to do a pull request...

-- Chris

**Comment by mpartel** [comment]
Good catch!

I think Postgres uses [float_to_shortest_decimal](https://doxygen.postgresql.org/shortest__dec_8h.html#aa71203831abca23681642212dd051565) internally. Let's maybe use that (or one of its variants).

A PR would be very welcome :+1:

**Comment by ghost** [comment]
Hi.

> I think Postgres uses float_to_shortest_decimal

Thanks, that looks good. I'll try to use that and do a PR this week end. Stay tuned.

-- Chris

**Comment by ghost** [comment]
> I'll try to use that and do a PR this week end. Stay tuned.

OK,

PR done :)

-- Chris

**Comment by mpartel** [comment]
Thanks!
Turns out  `double_to_shortest_decimal` doesn't exist yet in Postgres 11. I'll have to look into that some more before making a release.

**Comment by ghost** [comment]
> Thanks! Turns out `double_to_shortest_decimal` doesn't exist yet in Postgres 11. I'll have to look into that some more before making a release.

Oops, I did indeed test only on 13.
Both, `float_to_shortest_decimal` and `double_to_shortest_decimal` didn't exist yet in Postgres 11.

I see two possible solutions:

 - use `snprintf()` with something like %.7e and %.15e (to verify what the exact precisions are) for Postgres 11 only

 - drop support for Postgres 11 >:)

-- Chris

**Comment by mpartel** [comment]
Well, this turned out to be quite a yak shave, but the behaviour of Postgres functions `float4out` and `float8out` should now be replicated on 11 and later.

I didn't 100% verify those are the correct functions, but `float_to_shortest_decimal*` is only called from `float4out`, so I'm assuming they are.

[Releasing](https://github.com/mpartel/postgres-protobuf/actions/runs/2143965324) as 0.3.0.

Thanks!

**Comment by ghost** [comment]
Hi,

thanks for the very fast turn-around times. I can confirm 0.3.0 works for me on Postgres 13.

Thanks again :)
-- Chris
